package pss.config.runner;

public enum RunnerType {
    PSS_VARIABLE_GENERATING_RUNNER,
    PSS_GROUPING_RUNNER,
    USER_GENERATING_RUNNER,
    USER_GROUPING_RUNNER,
    REPORT_GENERATING_RUNNER,
    ANONYMIZING_RUNNER,
    DEANONYMIZING_RUNNER,
    FULL_SIMULATION_RUNNER,
    RESULT_FILTERING_RUNNER,
    FULL_SIMULATION_TILL_DECODING,
    FULL_SIMULATION_WITH_ADVERSARY,
    FULL_SIMULATION_WITH_ADVERSARY_TILL_DECODING,
    FULL_SIMULATION_WITH_GENERATED_ADVERSARY,
    FULL_SIMULATION_WITH_GENERATED_ADVERSARY_TILL_DECODING
}
