package pss.reader.config.runner;

import pss.config.runner.FullSimulationWithGeneratedAdversaryTillDecodingRunnerConfig;
import pss.exception.InvalidConfigException;
import pss.exception.PssException;
import pss.exception.ReaderException;

public interface FullSimulationWithGeneratedAdversaryTillDecodingRunnerConfigReadable {
    FullSimulationWithGeneratedAdversaryTillDecodingRunnerConfig generateFullSimulationWithGeneratedAdversaryTillDecodingRunnerConfig() throws InvalidConfigException, ReaderException, PssException;
}
